### ISSUE TITLE
main 分支 dtm-admin 缺少 vue-demi 包，打包错误

### ISSUE THREAD

**Issue by zzx131** [dtm-labs/dtm#323]
npm run build
> dtm-admin@0.0.0 build
> vite build && echo > dist/placeholder

vite v2.9.1 building for production...
transforming (34) src/layout/components/content.vue[@vue/compiler-sfc] ::v-deep usage as a combinator has been deprecated. Use :deep(<inner-selector>) instead.

✓ 39 modules transformed.
[vite]: Rollup failed to resolve import "vue-demi" from "src/views/Dashboard/GlobalTransactions/AllTransactions.vue".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "vue-demi" from "src/views/Dashboard/GlobalTransactions/AllTransactions.vue".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at onRollupWarning (/home/zzx/go-proj/GOPATH/src/dtm/admin/node_modules/vite/dist/node/chunks/dep-611778e0.js:39103:19)
    at onwarn (/home/zzx/go-proj/GOPATH/src/dtm/admin/node_modules/vite/dist/node/chunks/dep-611778e0.js:38919:13)
    at Object.onwarn (/home/zzx/go-proj/GOPATH/src/dtm/admin/node_modules/rollup/dist/shared/rollup.js:23129:13)
    at ModuleLoader.handleResolveId (/home/zzx/go-proj/GOPATH/src/dtm/admin/node_modules/rollup/dist/shared/rollup.js:22419:26)
    at /home/zzx/go-proj/GOPATH/src/dtm/admin/node_modules/rollup/dist/shared/rollup.js:22380:26
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

在package,json中加上  "vue-demi": "^0.13.1", 可以正常打包

"dependencies": {
    "ant-design-vue": "^3.1.1",
    "vue": "^3.2.25",
    "vue-demi": "^0.13.1",
    "vue-request": "^1.2.4"
  },

**Comment by yedf2** [comment]
目前我们采用的是yarn包管理，你试试yarn build。我在yarn.lock里面找到vue-demi的依赖
